# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iver3on
brief-intro: JAVA R&D Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iver3on.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: grepzwb
facebook_username: grepzwb
github_username: iver3on
email: grepzwb@qq.com
weibo_username: 传给3秒后的自己
zhihu_username: iver3on

description_footer: 知识积累，生活累积。

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
#duoshuo_shortname: #grepzwb
disqus_shortname: iver3on

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
#src = "//hm.baidu.com/hm.js?7dd1828002fc974ff9a454248030c30a";
# xxxxx字符串
baidu_tongji_id: dd1828002fc974ff9a454248030c30a
google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5
